### ISSUE TITLE
My modified save file isn't recognized by the game.

### ISSUE THREAD

**Issue by LukasOchiwo** [fendevel/P4G-Save-Tool#14]
I'm on an old update of the game (REV 2023 if it's important) and I modified my save file just to modify my stats and my inventory. I launched the game and there was no more save files. I thought the program just deleted my save file but  I got back in the save folder : data0001.bin was still here. Is it because the modified save file is meant for a later update ?

**Comment by bikeracer4487** [comment]
This is because when you modify the save file, it also modifies the MD5 checksum of that file, and P4G keeps a second file (dataXXXX.binslot) that contains what the MD5 SHOULD be, and when they don't match, it just doesn't show up in the game. There is a workaround that you can find here: https://gbatemp.net/threads/release-persona-4-golden-save-editor.437464/page-10#post-9094641

**Comment by LukasOchiwo** [comment]
Oh wow, ok ! Thanks a bunch ^^ !
